version: "3.8"

services:
  api:
    build:
      context: ./api
      target: dev
    hostname: localhost
    container_name: api_c
    ports:
      - "5000:5000"
    volumes:
      - ./api:/app
      - /app/node_modules

  web:
    build: ./web
    hostname: localhost
    container_name: web_c
    ports:
      - "3000:4173"
      - "3001:5173"
    volumes:
      - ./web:/app
      - /app/node_modules
